name: SpaceX Lambda CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      REGION_NAME: ${{ secrets.AWS_REGION }}
      ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DB_TABLE_NAME: launches

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: pytest tests/

    - name: Build Docker image
      run: docker build -t spacex .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Ensure S3 bucket exists
      run: |
        BUCKET_NAME=spacex-deploy-artifacts
        REGION=${{ secrets.AWS_REGION }}

        if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
          echo "Bucket '$BUCKET_NAME' no existe. Creando..."
          if [ "$REGION" = "us-east-1" ]; then
            aws s3api create-bucket --bucket "$BUCKET_NAME"
          else
            aws s3api create-bucket \
              --bucket "$BUCKET_NAME" \
              --region "$REGION" \
              --create-bucket-configuration LocationConstraint="$REGION"
          fi
        else
          echo "Bucket '$BUCKET_NAME' ya existe."
        fi

    - name: Deploy with AWS SAM
      run: |
        sam build
        sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --stack-name spacex-stack \
          --capabilities CAPABILITY_IAM \
          --s3-bucket spacex-deploy-artifacts